export const seedPostSlugs = [
  "adobe-commerce-vs-magento-open-source",
  "fix-magento-checkout-errors",
  "hyva-theme-complete-guide",
  "magento-2-upgrade-guide",
  "magento-speed-optimization-2026",
  "hire-magento-developer-europe",
  "magento-developer-rates-europe-2026",
  "adobe-commerce-agency-vs-freelancer-europe",
  "magento-hacked-emergency-recovery-guide",
  "magento-1-end-of-life-business-risks",
  "magento-payment-gateway-failures-troubleshooting",
  "magento-vs-shopify-for-complex-catalogs",
  "magento-development-cost-breakdown-2026",
  "adobe-commerce-b2b-features-checklist-2026",
  "magento-multi-store-architecture-guide",
  "magento-graphql-performance-optimization",
  "adobe-commerce-cloud-vs-self-hosted",
  "pwa-studio-vs-hyva-which-to-choose",
] as const;
